Add new prop: controlled
mathieudutour/react-progress-button pull request #80
Opened 2017-05-09 19:41 UTC by kristofferh

Sometimes you want to have full control of the state of the button - for example when keeping the state in `redux` or `redux-form`. Perhaps you only want to set loading to true while an action is dispatched and then set the button state based of the outcome of that call. Because the `react-progress-button` will always set itself to loading on click this gets difficult to achieve. This adds a new prop, `controlled`, which when set to true won't initiate loading (that's left to the caller).

2017-05-10 07:24 UTC, mathieudutour requested changes

2017-05-10 07:24 UTC, mathieudutour commented on src/index.js
> +      return true
you still want to call `this.props.onClick(e)` here

2017-05-10 13:30 UTC, kristofferh commented on src/index.js
> +      return true
Ah, yes. Updated.

2017-05-11 06:48 UTC, mathieudutour commented
thanks!

2017-05-11 06:48 UTC, merged