Updated dependency
mathieudutour/react-progress-button pull request #84
Opened 2017-10-02 18:43 UTC by adam-golab

Now it's using react v16.0.0 and webpack v3.6.0

2017-10-02 21:46 UTC, mathieudutour requested changes

2017-10-02 21:46 UTC, mathieudutour commented on example/src/app.js
> +
can you remove the extra line? it's making the linter unhappy

2017-10-02 21:47 UTC, mathieudutour commented
Cool thanks! Can you fix the small linter issue and I'll merge?

2017-10-03 06:09 UTC, adam-golab commented
Sure. Fixed

2017-10-03 06:46 UTC, merged